name: Build and Release one


on:
  push:
    tags:
      - "v*"
  #repository_dispatch:
  workflow_dispatch:

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: i386_pentium4_1907
            sdk_url_path: https://downloads.openwrt.org/releases/19.07.10/targets/x86/generic
            sdk_name: -sdk-19.07.10-x86-generic_
          - arch: i386_pentium4
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/x86/generic
            sdk_name: -sdk-23.05.5-x86-generic
          - arch: ramips_mt7621_1907
            sdk_url_path: https://downloads.openwrt.org/releases/19.07.10/targets/ramips/mt7621
            sdk_name: -sdk-19.07.10-ramips
          # - arch: arc_archs
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/archs38/generic
          #   sdk_name: -sdk-archs38-generic_
          # - arch: armeb_xscale
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ixp4xx/generic
          #   sdk_name: -sdk-ixp4xx-generic_
          # - arch: powerpc_464fp
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/apm821xx/nand
          #   sdk_name: -sdk-apm821xx-nand_
          # - arch: powerpc_8540
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mpc85xx/generic
          #   sdk_name: -sdk-mpc85xx-generic_

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:cache:

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -yq gettext libncurses5-dev xsltproc  python2

      - name: Prepare SDK Home
        run: |
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Build package
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
        run: sh compile.sh

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.62.1
          files: "*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
